import { Role } from "@/types/enums";
import { Users, BookOpen, UserCheck, CreditCard, BarChart, Settings, Home, Bell, FileText, ClipboardList, TrendingUp, GraduationCap, Archive, ListTodo, CalendarOff } from "lucide-react";

export const navigationConfig: Partial<Record<Role, { title: string; href: string; icon: React.ElementType }[]>> = {
  SUPER_ADMIN: [
    { title: "Dashboard", href: "/management", icon: Home },
    { title: "Finance", href: "/finance", icon: CreditCard },
    { title: "Notices", href: "/notices", icon: Bell },
    { title: "Reports", href: "/reports", icon: BarChart },
    { title: "Alumni Directory", href: "/alumni", icon: GraduationCap },
    { title: "Settings", href: "/settings", icon: Settings },
  ],
  MANAGEMENT: [
    { title: "Dashboard", href: "/management", icon: Home },
    { title: "Students", href: "/students", icon: Users },
    { title: "Parents", href: "/parents", icon: Users },
    { title: "Staff", href: "/staff", icon: UserCheck },
    { title: "Finance", href: "/finance", icon: CreditCard },
    { title: "Notices", href: "/notices", icon: Bell },
    { title: "Reports", href: "/reports", icon: BarChart },
    { title: "Alumni Directory", href: "/alumni", icon: GraduationCap },
    { title: "Leave", href: "/leave", icon: CalendarOff },
    { title: "Settings", href: "/settings/general", icon: Settings },
  ],
  PRINCIPAL: [
    { title: "Dashboard", href: "/principal", icon: Home },
    { title: "Students", href: "/students", icon: Users },
    { title: "Parents", href: "/parents", icon: Users },
    { title: "Attendance", href: "/attendance", icon: UserCheck },
    { title: "Routines", href: "/routines", icon: ListTodo },
    { title: "Finance", href: "/finance", icon: CreditCard },
    { title: "Exams", href: "/exams", icon: FileText },
    { title: "Marks", href: "/marks", icon: ClipboardList },
    { title: "Results", href: "/results", icon: TrendingUp },
    { title: "Notices", href: "/notices", icon: Bell },
    { title: "Promotions", href: "/promotion", icon: Archive },
    { title: "Alumni Directory", href: "/alumni", icon: GraduationCap },
    { title: "Leave", href: "/leave", icon: CalendarOff },
    { title: "Settings", href: "/settings/academic", icon: Settings },
  ],
  TEACHER: [
    { title: "Dashboard", href: "/teacher", icon: Home },
    { title: "Attendance", href: "/attendance", icon: UserCheck },
    { title: "Study Materials", href: "/study-materials", icon: BookOpen },
    { title: "Homework", href: "/homework", icon: FileText },
    { title: "Routines", href: "/routines", icon: ListTodo },
    { title: "Marks", href: "/marks", icon: ClipboardList },
    { title: "Results", href: "/results", icon: TrendingUp },
    { title: "Collect Fees", href: "/finance", icon: CreditCard },
    { title: "Leave", href: "/teacher/leave", icon: CalendarOff },
  ],
  PARENT: [
    { title: "Dashboard", href: "/parent", icon: Home },
    { title: "Attendance", href: "/parent/attendance", icon: UserCheck },
    { title: "Daily Routine", href: "/parent/routines", icon: ListTodo },
    { title: "Study Materials", href: "/parent/study-materials", icon: BookOpen },
    { title: "Homework", href: "/parent/homework", icon: FileText },
    { title: "Fees", href: "/parent/fees", icon: CreditCard },
    { title: "Results", href: "/parent/results", icon: TrendingUp },
    { title: "Leave", href: "/parent/leave", icon: CalendarOff },
  ],
  ALUMNI: [
    { title: "Dashboard", href: "/alumni", icon: Home },
    { title: "Donations", href: "/alumni/donations", icon: CreditCard },
    { title: "News", href: "/alumni/news", icon: Bell },
  ]
};
